apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-pipelines-ms-app
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: deploy-pipelines-ms-app
  template:
    metadata:
      labels:
        app: deploy-pipelines-ms-app
    spec:
      containers:
      - name: my-container
        image: us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/my-repo/$IMAGE_NAME:$IMAGE_TAG
        ports:
        - containerPort: 80  
---
apiVersion: v1
kind: Service
metadata:
  name: deploy-pipelines-ms-app-service
spec:
  selector:
    app: deploy-pipelines-ms-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
